### ISSUE TITLE
Crash when language is set to turkish

### ISSUE THREAD

**Issue by Agraphie** [hbb20/CountryCodePickerProject#110]
Hi,

the app I'm using is crashing when using your library and the phone is set to turkish and you enter any character in the search view.

```Java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
	 at com.hbb20.Country.isEligibleForQuery(Country.java:1119)
	 at com.hbb20.CountryCodeAdapter.getFilteredCountries(CountryCodeAdapter.java:157)
	 at com.hbb20.CountryCodeAdapter.applyQuery(CountryCodeAdapter.java:144)
	 at com.hbb20.CountryCodeAdapter.access$000(CountryCodeAdapter.java:28)
	 at com.hbb20.CountryCodeAdapter$2.onTextChanged(CountryCodeAdapter.java:90)
	 at android.widget.TextView.sendOnTextChanged(TextView.java:8186)
	 at android.widget.TextView.handleTextChanged(TextView.java:8248)
	 at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10370)
	 at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1208)
	 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
	 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
	 at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	 at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:223)
	 at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:136)
	 at android.widget.TextView.doKeyDown(TextView.java:6284)
	 at android.widget.TextView.onKeyDown(TextView.java:6074)
	 at android.view.KeyEvent.dispatch(KeyEvent.java:2676)
	 at android.view.View.dispatchKeyEvent(View.java:9880)
	 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
	 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
	 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
	 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
	 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
	 at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:403)
	 at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1800)
	 at android.app.Dialog.dispatchKeyEvent(Dialog.java:757)
	 at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:317)
	 at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4327)
	 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4298)
	 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
	 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
	 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
	 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
	 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
	 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
	 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
	 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
	 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
	 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
	 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
	 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
	 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
	 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4028)
	 at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4189)
	 at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2365)
	 at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1961)
	 at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1952)
	 at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2342)
	 at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	 at android.os.MessageQueue.nativePollOnce(Native Method)
	 at android.os.MessageQueue.next(MessageQueue.java:323)
	 at android.os.Looper.loop(Looper.java:136)
	 at android.app.ActivityThread.main(ActivityThread.java:6077)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

Any ideas on how to prevent this? Thanks in advance!

**Comment by hbb20** [comment]
Does it work correctly for other languages?

**Comment by Agraphie** [comment]
It works if English or German (or so) is selected. It's easily reproducible by setting the emulator (or any device) to Turkish and launching the example app. Then click on "introduction", select a country and type any letter and the app crashes.

**Comment by hbb20** [comment]
@Agraphie  thank you for the PL. version 2.0.7 is published with the fix.
