### ISSUE TITLE
App Crashed When The Activity Containing CCP was opened.

### ISSUE THREAD

**Issue by anupsunni** [hbb20/CountryCodePickerProject#143]
`01-04 12:25:14.832 15354-15354/com.asrtech.XXX E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.asrtech.XXX, PID: 15354
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.isProjected()' on a null object reference
                                                                       at android.graphics.drawable.LayerDrawable.isProjected(LayerDrawable.java:357)
                                                                       at android.view.View.invalidateInternal(View.java:13931)
                                                                       at android.view.View.invalidate(View.java:13891)
                                                                       at android.view.View.setFrame(View.java:18029)
                                                                       at android.view.View.layout(View.java:17934)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                       at android.view.View.layout(View.java:17938)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                       at android.view.View.layout(View.java:17938)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17938)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                       at android.view.View.layout(View.java:17938)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17938)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
                                                                       at android.view.View.layout(View.java:17938)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5814)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2667)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2368)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1438)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7398)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:158)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by hbb20** [comment]
Is this persistent? 
Can you show us your gradle file?

**Comment by hbb20** [comment]
Most probably you are using `parent="@android:style/Theme.Holo.Light.DarkActionBar"` as your app theme's parent. Nowadays it is recommended to switch to parent theme `parent="Theme.AppCompat.Light.DarkActionBar"`. This will let you use latest Android features in your app and also fixes this error.

**If you do not want change your Theme parent**, here is a workaround:
1. Download the zip file using this link => https://goo.gl/c6usWS
2. Extract the zip file you will get one, folder named "drawable-v21"
3. Copy this folder and paste it into your project's **res/** folder. (<YourProject>/app/src/main/res/drawable-v21) _If you already have this folder, simply merge this new folder with your existing one._
5. Rebuild the project
6. Run the app

**Comment by hbb20** [comment]
Thank you for the email reply. 👍

**Comment by anupsunni** [comment]
Thanks

**Comment by Pinjari** [comment]
> Most probably you are using `parent="@android:style/Theme.Holo.Light.DarkActionBar"` as your app theme's parent. Nowadays it is recommended to switch to parent theme `parent="Theme.AppCompat.Light.DarkActionBar"`. This will let you use latest Android features in your app and also fixes this error.
> 
> **If you do not want change your Theme parent**, here is a workaround:
> 
> 1. Download the zip file using this link => https://goo.gl/c6usWS
> 2. Extract the zip file you will get one, folder named "drawable-v21"
> 3. Copy this folder and paste it into your project's **res/** folder. (/app/src/main/res/drawable-v21) _If you already have this folder, simply merge this new folder with your existing one._
> 4. Rebuild the project
> 5. Run the app

Thanks, It is working now
