### ISSUE TITLE
NullPointerException com.hbb20.Country.getPhoneCode() at CountryCodePicker.java:545

### ISSUE THREAD

**Issue by viktord1985** [hbb20/CountryCodePickerProject#158]
I got

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.hbb20.Country.getPhoneCode()' on a null object reference
                                                                           at com.hbb20.CountryCodePicker.setSelectedCountry(CountryCodePicker.java:545)
                                                                           at com.hbb20.CountryCodePicker.setFullNumber(CountryCodePicker.java:1254) 
countryCodePicker.setFullNumber(phoneNumber);

when called countryCodePicker.setFullNumber(phoneNumber); where phoneNumber is number without country code

So when setSelectedCountry(Country selectedCountry) called selectedCountry is null.
In this method Country.getCountryForCode returns null because defaultCountryCode = 0 and I don't use setDefaultCountryUsingPhoneCode() because it's deprecated

Crash may happen in lines: 528, 534, 536 ... because selectedCountry is null

**Comment by hbb20** [comment]
Thank you for finding and reporting. A possible problem is fixed in version 2.1.5. This you find this problem persists with the new version, please comment back with the phoneNumber you are trying to put in.

I would like to mention a couple of things here:
- Setting default country using name code is generally a good idea. Even if `setDefaultCountryUsingPhoneCode()` is deprecated, you always can use `setDefaultCountryUsingNameCode()`. [Read more.](https://github.com/hbb20/CountryCodePickerProject/wiki/Default-Country)

- Usually `countryCodePicker.setFullNumber(phoneNumber);` expects a full number including national code to work correctly.
