### ISSUE TITLE
crash when use lib 

### ISSUE THREAD

**Issue by Vullett** [hbb20/CountryCodePickerProject#17]
when i try to use library and i use cardview the app crash and give this errors
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.internal.widget.TintManager" on path: DexPathList[[zip file "/data/app/com.vullett.weno-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]

**Comment by hbb20** [comment]
This does not look like library specific issue.
Try following:
1. Clean project 
2. Rebuild project
3. Run. (Mostly this should work) 

Post your result in comment.

**Comment by Vullett** [comment]
unfortunately, the same problem and when i delete the lib every thing works fine, appreciate your support sir
11-16 16:07:20.952 18864-18864/com.vullett.weno E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.vullett.weno, PID: 18864
                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/widget/TintManager;
                                                                      at android.support.design.widget.TabLayout$Tab.setIcon(TabLayout.java:953)
                                                                      at com.vullett.weno.HomeActivity.onCreate(HomeActivity.java:1168)
                                                                      at android.app.Activity.performCreate(Activity.java:6020)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5349)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.internal.widget.TintManager" on path: DexPathList[[zip file "/data/app/com.vullett.weno-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                      at android.support.design.widget.TabLayout$Tab.setIcon(TabLayout.java:953) 
                                                                      at com.vullett.weno.HomeActivity.onCreate(HomeActivity.java:1168) 
                                                                      at android.app.Activity.performCreate(Activity.java:6020) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391) 
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:135) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5349) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) 
                                                                  	Suppressed: java.lang.ClassNotFoundException: android.support.v7.internal.widget.TintManager
                                                                      at java.lang.Class.classForName(Native Method)
                                                                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                      		... 16 more
                                                                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available


also the line from home activity which have a crash of it 
        tabLayout.addTab(tabLayout.newTab().setIcon(R.drawable.favourates_white));

and the resource found and no problem, appreciate your help

**Comment by hbb20** [comment]
Well this is interesting. Can you share your project repository with me (harshbbhakta@gmail.com) so that I can check at my end?

**Comment by Vullett** [comment]
Dear sir,
thanks for you help i think i solved it by the following issues for who face the same in the future do the following:

for dependencies must use them all the same or as follows i solve the problem:
compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:cardview-v7:23.0.0'
    compile 'com.android.support:design:23.+'

also for xml you must check the resources for any images of text to be matched and not have a bug in them like this:
            sched.setImageRight("" + R.drawable.khaled);
when you pass a value in a model object of data 


thanks for you sir, appreciate your good work in the library too :)

**Comment by hbb20** [comment]
Yeah, library version conflict should be taken care. Nice to see that you solved it :+1:
