### ISSUE TITLE
android:digits="15" in EditText XML crashes app

### ISSUE THREAD

**Issue by Obsttube** [hbb20/CountryCodePickerProject#212]
Thank you for that lib! It's awesome.

ver: com.hbb20:ccp:**2.2.0**
issue:
When I set **android:digits="15"** in EditText in XML, when user types 555 then app crashes. (+48 PL)
Firstly I thought that :digits is to set max length, but I was wrong. Anyway, I found a bug that probably isn't a problem cuz who limits allowed digits in a phone number, right? But in case u want to fix it, here is the error:
<details><summary>(Click to expand)</summary>
`java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 3
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
        at android.text.Selection.setSelection(Selection.java:76)
        at android.text.Selection.setSelection(Selection.java:87)
        at com.hbb20.InternationalPhoneTextWatcher.afterTextChanged(InternationalPhoneTextWatcher.java:155)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:8243)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10422)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
        at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
        at android.widget.TextView.doKeyDown(TextView.java:6311)
        at android.widget.TextView.onKeyDown(TextView.java:6101)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2761)
        at android.view.View.dispatchKeyEvent(View.java:9876)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:403)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1816)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3050)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:317)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4351)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4322)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3855)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3874)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4019)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3882)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4076)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3855)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3874)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3882)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3855)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6234)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6208)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6169)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3650)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6111)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`
</details>

**Comment by hbb20** [comment]
@Obsttube, thank you for reporting. We believe some crashes are important if they show a potential problem with our code.
Like this in your case.
1. `digits` restricts the allowed character. While doing phone number formatting, ccp might add some special characters that are not specified in `Digits`.
2. In order to allow only valid number, a developer might set a strict limit on input size but it is problem again. Specific length does not ensure the validity of number. Different countries have different lengths of carrier number and formatted phone number's length might differ from plain number, if auto formatting is enabled then it won't work as expected. **Instead of length restrictions, developer should use `ccp.isValidFullNumber()` to validate the number.**

In any case, it is better to get crash in developing phase so that it can be corrected asap and the quality app goes for production.
