### ISSUE TITLE
NullPointerException: CCPCountry.java - String.toLowerCase()' on a null object reference

### ISSUE THREAD

**Issue by marcinOz** [hbb20/CountryCodePickerProject#231]
Hi, we noticed a crash. 
version: 2.2.2
stack trace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
       at com.hbb20.a.g(CCPCountry.java:1196)
       at com.hbb20.c.b(CountryCodeAdapter.java:171)
       at com.hbb20.c.a(CountryCodeAdapter.java:144)
       at com.hbb20.c.a(CountryCodeAdapter.java:28)
       at com.hbb20.c$2.onTextChanged(CountryCodeAdapter.java:90)
       at android.widget.TextView.sendOnTextChanged(TextView.java:9589)
       at android.widget.TextView.handleTextChanged(TextView.java:9676)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12257)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1256)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:848)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:344)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by rolgalan** [comment]
Hi, we're also getting reports of several crashes like this with the 2.2.2 version. We couldn't reproduce it yet.
Here you can see the deobfuscated stacktrace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
       at com.hbb20.CCPCountry.isEligibleForQuery(CCPCountry.java:1196)
       at com.hbb20.CountryCodeAdapter.getFilteredCountries(CountryCodeAdapter.java:171)
       at com.hbb20.CountryCodeAdapter.applyQuery(CountryCodeAdapter.java:144)
       at com.hbb20.CountryCodeAdapter.access$000(CountryCodeAdapter.java:28)
       at com.hbb20.CountryCodeAdapter$2.onTextChanged(CountryCodeAdapter.java:90)
       at android.widget.TextView.sendOnTextChanged(TextView.java:9403)
```

**Comment by ksc91u** [comment]
I add this file to my app module

app/src/main/res/raw/keep.xml

`
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:shrinkMode="strict"
    tools:keep="@raw/*"/>
`

build with proguard 
`
minifyEnabled true
shrinkResources true
`

don't crash anymore.

**Comment by hbb20** [comment]
This looks more like proguard issue and related to #227. Next version will have keep.xml to avoid this.

**Comment by hbb20** [comment]
Please update to version >2.2.3. Theoretically it should solve this issue. If issue is not resolved after upgrading,  feel free to report back to this issue.

**Comment by Mihir3646** [comment]
> Please update to version >2.2.3. Theoretically it should solve this issue. If issue is not resolved after upgrading, feel free to report back to this issue.

Where is Keep.xml? Not able to find it.

**Comment by hbb20** [comment]
This should open that file:
https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/res/raw/keep.xml
