### ISSUE TITLE
 app crash using proguard   during write name of country in search field

### ISSUE THREAD

**Issue by enggazzar** [hbb20/CountryCodePickerProject#254]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
       at com.hbb20.CCPCountry.log(Unknown Source)
       at com.hbb20.CountryCodeAdapter.setQueryClearListener(Unknown Source)
       at com.hbb20.CountryCodeAdapter.setSearchBar(Unknown Source)
       at com.hbb20.CountryCodeAdapter.setSearchBar(Unknown Source)
       at com.hbb20.CountryCodeAdapter$2.onTextChanged(Unknown Source)
       at android.widget.TextView.sendOnTextChanged(TextView.java:7991)
       at android.widget.TextView.handleTextChanged(TextView.java:8053)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10157)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1033)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:559)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)

**Comment by enggazzar** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
       at com.hbb20.CCPCountry.log(Unknown Source)
       at com.hbb20.CountryCodeAdapter.setQueryClearListener(Unknown Source)
       at com.hbb20.CountryCodeAdapter.setSearchBar(Unknown Source)
       at com.hbb20.CountryCodeAdapter.setSearchBar(Unknown Source)
       at com.hbb20.CountryCodeAdapter$2.onTextChanged(Unknown Source)
       at android.widget.TextView.sendOnTextChanged(TextView.java:7991)
       at android.widget.TextView.handleTextChanged(TextView.java:8053)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10157)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1033)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:559)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)

**Comment by hbb20** [comment]
Can you please post what is the version number of CCP that you are using?

**Comment by enggazzar** [comment]
latest

**Comment by hbb20** [comment]
This should have been fixed in latest version. Still I will check it. Meanwhile, refer this issue https://github.com/hbb20/CountryCodePickerProject/issues/231

**Comment by enggazzar** [comment]
thanks  work fine now
