### ISSUE TITLE
Resources NotFoundException

### ISSUE THREAD

**Issue by prashantarvind** [hbb20/CountryCodePickerProject#275]
found crash on activity start

Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at com.hbb20.CountryCodePicker.init(CountryCodePicker.java:183)
        at com.hbb20.CountryCodePicker.<init>(CountryCodePicker.java:148)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.make.my.wish.makemywish.PhoneVerificationActivity.onCreate(PhoneVerificationActivity.java:23) 
        at android.app.Activity.performCreate(Activity.java:6001) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368) 
        at android.app.ActivityThread.access$800(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5233) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at com.hbb20.CountryCodePicker.init(CountryCodePicker.java:183) 
        at com.hbb20.CountryCodePicker.<init>(CountryCodePicker.java:148) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.make.my.wish.makemywish.PhoneVerificationActivity.onCreate(PhoneVerificationActivity.java:23) 
        at android.app.Activity.performCreate(Activity.java:6001) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368) 
        at android.app.ActivityThread.access$800(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5233) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693) 
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/ccp_selectable_bg.xml from drawable resource ID #0x7f07005e
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2428)
        at android.content.res.Resources.loadDrawable(Resources.java:2330)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
        at android.view.View.<init>(View.java:3731)
        at android.view.ViewGroup.<init>(ViewGroup.java:492)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:249)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:245)
    	at android.widget.RelativeLayout.<init>(Rel

**Comment by hbb20** [comment]
Just to make sure, you synced project before installing in device, right?
Can you please re-sync and rebuild the project?

**Comment by rakeshdausa** [comment]
@hbb20 I am also getting resource not found exception in some devices in production 
`android.content.res.ResourcesImpl.getResourceName (ResourcesImpl.java:260)
android.content.res.ResourcesImpl.loadDrawableForCookie (ResourcesImpl.java:774)
android.content.res.ResourcesImpl.loadDrawable (ResourcesImpl.java:640)
android.content.res.MiuiResourcesImpl.loadDrawable (MiuiResourcesImpl.java:316)
android.content.res.Resources.loadDrawable (Resources.java:900)
android.content.res.TypedArray.getDrawableForDensity (TypedArray.java:955)
android.content.res.TypedArray.getDrawable (TypedArray.java:930)
android.widget.ImageView.<init> (ImageView.java:190)
android.widget.ImageView.<init> (ImageView.java:173)
android.support.v7.widget.AppCompatImageView.<init> (AppCompatImageView.java:72)
android.support.v7.widget.AppCompatImageView.<init> (AppCompatImageView.java:68)
android.support.v7.app.AppCompatViewInflater.createImageView (AppCompatViewInflater.java:182)
android.support.v7.app.AppCompatViewInflater.createView (AppCompatViewInflater.java:106)
android.support.v7.app.AppCompatDelegateImpl.createView (AppCompatDelegateImpl.java:1266)
android.support.v7.app.AppCompatDelegateImpl.onCreateView (AppCompatDelegateImpl.java:1316)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:776)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:734)
android.view.LayoutInflater.rInflate (LayoutInflater.java:867)
android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:828)
android.view.LayoutInflater.rInflate (LayoutInflater.java:870)
android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:828)
android.view.LayoutInflater.inflate (LayoutInflater.java:519)
android.view.LayoutInflater.inflate (LayoutInflater.java:427)
com.hbb20.CountryCodePicker.init (CountryCodePicker.java:183)
com.hbb20.CountryCodePicker.<init> (CountryCodePicker.java:148)
java.lang.reflect.Constructor.newInstance0 (Constructor.java)
java.lang.reflect.Constructor.newInstance (Constructor.java:334)
android.view.LayoutInflater.createView (LayoutInflater.java:651)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:794)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:734)
android.view.LayoutInflater.rInflate (LayoutInflater.java:867)
android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:828)
android.view.LayoutInflater.rInflate (LayoutInflater.java:870)
android.view.LayoutInflater.rInflateChildren (LayoutInflater.java:828)
android.view.LayoutInflater.inflate (LayoutInflater.java:519)
android.view.LayoutInflater.inflate (LayoutInflater.java:427)`

This is due to imageview 
`Binary XML file line #52: Error inflating class ImageView`

Affected devices are `Redmi Note 5 Pro`, `samsung SM-G960W`, 'Nexus 6P' and 'Moto E (4) Plus' 
Working on other devices fine.

**Comment by hbb20** [comment]
Gradle file and android version on crashing and non-crashing devices will be helpful.

**Comment by rakeshdausa** [comment]
Android version is 7.0, 7.1.1, 8.0.0, 8.1.0 but strange thing is not crashing on all devices of same android version. Crashing on `Redmi Note 5 Pro`, `samsung SM-G960W`, `Nexus 6P` and `Moto E (4) Plus`. 
I am shipping app as android app bundle (aab) to playstore is it the cause of this?

**Comment by hbb20** [comment]
I tried to reproduce it with an emulator running on version 4.4.x but could not reproduce.

However, I tried to fix possible issues. But I want your help to check if it is a real fix.
2.2.7.1, 
2.2.7.2,
2.2.7.3,
2.2.7.4

are the version I uploaded with different possible fixes. I want you to try these versions where v2.2.7 was causing a crash. Please list which of above 4 worked and which one did not work.

@rakeshdausa  , @prashantarvind ,  please post on #296 if you will be able to test this. I appreciate your help.
