### ISSUE TITLE
App Crashes when trying to open a popup window containing a CCP

### ISSUE THREAD

**Issue by s3603079** [hbb20/CountryCodePickerProject#276]
**Error Log**

2018-12-28 11:35:58.608 2312-2312/com.example.liammc.yarn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.liammc.yarn, PID: 2312
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.isProjected()' on a null object reference
        at android.graphics.drawable.LayerDrawable.isProjected(LayerDrawable.java:422)
        at android.view.View.invalidateInternal(View.java:16758)
        at android.view.View.invalidate(View.java:16718)
        at android.view.View.setFrame(View.java:21068)
        at android.view.View.layout(View.java:20961)
        at android.view.ViewGroup.layout(ViewGroup.java:6440)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6440)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6440)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20964)
        at android.view.ViewGroup.layout(ViewGroup.java:6440)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3027)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2714)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1843)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7978)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

I tried all the fixes in the issue (https://github.com/hbb20/CountryCodePickerProject/issues/217)
however I'm still getting the error.

I tried putting the CCP in a normal layout and it works fine but in the popup layout it doesn't. This makes me believe that the popup window is the problem. However I'm quite new to android so i might be wrong. If I've missed some details please don't hesitate to ask.

**Comment by hbb20** [comment]
Oh.. It's interesting if you already tried Theme change and drawable zip and still it's persistent. Just to make sure, after applying solution in #127 you should to sync and rebuild project. 

If this does not go away, show me gradle file and if possible send github project link.

**Comment by liammcintosh97** [comment]
yea I tried applying all the solutions in #217 but to no avail

here is my app level gradle file

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.liammc.yarn"
        minSdkVersion 19
        targetSdkVersion 28
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
    implementation 'com.google.android.gms:play-services-places:16.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:customtabs:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.firebase:firebase-core:16.0.6'
    implementation 'com.google.firebase:firebase-auth:16.1.0'
    implementation 'com.google.firebase:firebase-database:16.0.5'
    implementation 'com.google.firebase:firebase-storage:16.0.5'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    implementation 'com.twitter.sdk.android:twitter:3.1.1'
    implementation 'com.twitter.sdk.android:twitter-core:3.1.1'
    implementation 'com.twitter.sdk.android:tweet-ui:3.1.1'
    implementation 'com.twitter.sdk.android:tweet-composer:3.1.1'
    implementation 'com.twitter.sdk.android:twitter-mopub:3.1.1'
    implementation('com.hbb20:ccp:2.2.3', {
        exclude group: 'com.android.support'
    })
    implementation 'com.android.support:multidex:1.0.3'
}

**Comment by liammcintosh97** [comment]
Ok so with the gradle change...

    implementation('com.hbb20:ccp:2.2.3', {
        exclude group: 'com.android.support'
    })

and the addition of the new drawable I was able to get the popupwindow to display however now when i click on the CCP i get this error and crash...

2019-01-05 12:49:22.170 7734-7734/com.example.liammc.yarn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.liammc.yarn, PID: 7734
    android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:982)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:384)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:101)
        at android.app.Dialog.show(Dialog.java:430)
        at com.hbb20.CountryCodeDialog.openCountryCodeDialog(CountryCodeDialog.java:248)
        at com.hbb20.CountryCodePicker.launchCountrySelectionDialog(CountryCodePicker.java:1956)
        at com.hbb20.CountryCodePicker.launchCountrySelectionDialog(CountryCodePicker.java:1948)
        at com.hbb20.CountryCodePicker$1.onClick(CountryCodePicker.java:130)
        at android.view.View.performClick(View.java:6935)
        at android.view.View$PerformClick.run(View.java:26211)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by liammcintosh97** [comment]
With a bit of googling I managed to come to a solution myself and now the CCP seems to work perfectly.  My latest problem wasn't caused by the CCP but by the way I was initializing the pop window.

Here is the solution that i used...
https://stackoverflow.com/a/50716727
