### ISSUE TITLE
NullPointerException when no country of preference

### ISSUE THREAD

**Issue by ndal** [hbb20/CountryCodePickerProject#310]
When using the xml property  `app:ccpDialog_initialScrollToSelection`,  a NullPointerException is launched if there is no country of preference.

Version of the libary: 2.2.9.

Stack trace : 
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.hbb20.CountryCodeDialog.openCountryCodeDialog(CountryCodeDialog.java:226)
        at com.hbb20.CountryCodePicker.launchCountrySelectionDialog(CountryCodePicker.java:2088)
        at com.hbb20.CountryCodePicker$1.onClick(CountryCodePicker.java:134)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)```

**Comment by hbb20** [comment]
Thank you so much for reporting. I will look into it....

**Comment by hbb20** [comment]
We found the problem and will fix in the  next version. Thank you so much for reporting.

**Comment by ndal** [comment]
Perfect, thank you for being so quick!

**Comment by ndal** [comment]
Is there an ETA for this next release?

**Comment by ndal** [comment]
Is there an ETA for this next release @hbb20?
