### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by RameshbabuJaga** [hbb20/CountryCodePickerProject#312]
Hi there, am using this lib and getting the above error when i am passing this mobile number +91 987654321. I don't know why substring indexing throwing null string.

`
 java.lang.NumberFormatException: For input string: ""
at java.lang.Integer.parseInt(Integer.java:620)
at java.lang.Integer.parseInt(Integer.java:643)
at com.hbb20.CCPCountry.getCountryForNumber(CCPCountry.java:344)
at com.hbb20.CountryCodePicker.setFullNumber(CountryCodePicker.java:1766)
at com.app.app.Activities.ProfileActivity$3.onResponse(ProfileActivity.java:222)
updateFormattingTextWatcher: EditText not registered CCP_last_selection
EditText for carrier number is not registered. Register it using registerCarrierNumberEditText() before getFullNumber() or setFullNumber().
`

**Comment by hbb20** [comment]
It looks like you have not registered carrierNumberEditText. You can set the edit text using `registerCarrierNumberEditText()`. For more details, check [wiki page](https://github.com/hbb20/CountryCodePickerProject/wiki/Full-Number-Support#1-setup).
