### ISSUE TITLE
W/System.err: java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by tsvelichkov** [hbb20/CountryCodePickerProject#331]
`W/System.err: java.lang.NumberFormatException: For input string: ""
W/System.err:     at java.lang.Integer.parseInt(Integer.java:627)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.hbb20.CCPCountry.getCountryForNumber(CCPCountry.java:344)
        at com.hbb20.CountryCodePicker.setFullNumber(CountryCodePicker.java:1766)
        at com.rentila.landlord.fragments.TenantEditFragment$TenantEditPageFragment.onCreateView(TenantEditFragment.java:499)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
W/System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)`

The phone number is: +359888858888

Investigating the library code it seems like the loop for getCountryForNumber is trying to cast "" to integer on the first iteration. 

The field is populated ok. It is just the exception showing in the log

**Comment by hbb20** [comment]
Thank you for reporting. We just released new version `v2.3.0` with the fix. Please check and let us know if it does not work as expected.
