### ISSUE TITLE
EditText without hint 

### ISSUE THREAD

**Issue by tsvelichkov** [hbb20/CountryCodePickerProject#333]
Having an EditText without hint causes NPE in 2.3.0

`W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
        at com.hbb20.CountryCodePicker.setEditText_registeredCarrierNumber(CountryCodePicker.java:1131)
        at com.hbb20.CountryCodePicker.registerCarrierNumberEditText(CountryCodePicker.java:1737)`

Adding an empty android:hint="" fixes the issue but causes warning in the studio

**Comment by hbb20** [comment]
Thanks for reporting. It's now fixed in v2.3.1.
