### ISSUE TITLE
A lot of Crashes Error inflating class com.hbb20.CountryCodePicker on v 2.3.3

### ISSUE THREAD

**Issue by assadyouness** [hbb20/CountryCodePickerProject#355]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dailyraffle/com.freecashoutapp.freecashout.activities.RegisterActivity}: android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class com.hbb20.CountryCodePicker
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Caused by android.view.InflateException: Binary XML file line #90: Binary XML file line #90: Error inflating class com.hbb20.CountryCodePicker
       at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
       at com.freecashoutapp.freecashout.fragments.RegisterFragment.onCreateView(RegisterFragment.java:162)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
       at com.freecashoutapp.freecashout.activities.BaseActivity.onStart(BaseActivity.java:65)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1266)
       at android.app.Activity.performStart(Activity.java:6943)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3276)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Android v  6.0.1
 Galaxy J5

**Comment by assadyouness** [comment]
Crashes on these devices: 

Android v 5.1 A1601
Android v 5.1  Mi 9X
Android v 6.0.1 Galaxy J5
Android v 7.1.2 TaintArt for x86

**Comment by hbb20** [comment]
Sorry to hear that....  My best guess is this might be related to AndroidX migration. If you have these devices handy, can you please check if v2.2.9 is working where 2.3.3 is crashing?

**Comment by hbb20** [comment]
Any update sir?

**Comment by jignesh8992** [comment]
I am also facing this crash @assadyouness have you solved it???? please update it @hbb20 sir.

**Comment by hbb20** [comment]
@jignesh8992 , I want to fix this. I will need your help to fix this.. I am not able to reproduce this. Can you share the project or create a demo project that can reproduce? That will be helpful..

**Comment by hbb20** [comment]
Can you check if v2.2.9 is working?

**Comment by hbb20** [comment]
Is your app on AndroidX?

**Comment by victoryang00** [comment]
> Crashes on these devices:
> 
> Android v 5.1 A1601
> Android v 5.1 Mi 9X
> Android v 6.0.1 Galaxy J5
> Android v 7.1.2 TaintArt for x86

could you provide the Taint art environment for testing?
