### ISSUE TITLE
Error inflating class com.hbb20.CountryCodePicker 

### ISSUE THREAD

**Issue by NateBarak** [hbb20/CountryCodePickerProject#371]
Device: samsung sm-g930k
Version: api 25
Library version: 2.2.4

Error:

data:text/text;charset=utf-8,
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.package.censored}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class com.hbb20.CountryCodePicker
	 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2668)
	 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
	 at android.app.ActivityThread.-wrap12(ActivityThread.java)
	 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
	 at android.os.Handler.dispatchMessage(Handler.java:102)
	 at android.os.Looper.loop(Looper.java:154)
	 at android.app.ActivityThread.main(ActivityThread.java:6169)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

Caused by: 
android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class com.hbb20.CountryCodePicker

Caused by: 
android.view.InflateException: Binary XML file line #11: Error inflating class com.hbb20.CountryCodePicker

Caused by: 
java.lang.reflect.InvocationTargetException
	 at java.lang.reflect.Constructor.newInstance0(Native Method)
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	 at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	 at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	 at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	 at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)

Caused by: 
android.view.InflateException: Binary XML file line #52: Binary XML file line #52: Error inflating class ImageView

Caused by: 
android.view.InflateException: Binary XML file line #52: Error inflating class ImageView

Caused by: 
android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f070081

I can't reproduce as it's a bug that happened to one of my users.
Any idea what can cause the issue? Thanks!

**Comment by henrique-thomazi** [comment]
My Android 5 users cannot start the activity that inflates the country code picker. I have the same stack trace and can reproduce it consistently.

**Comment by hbb20** [comment]
Thank you for reporting. It seems like this issue is similar to #403. It will be helpful if we continue discussion on a single thread. Further discussion can be found on #403.
@henrique-thomazi, looks like you were able to reproduce this on your physical device. Do you mind helping me solve this issue? Please post on #403

**Comment by hbb20** [comment]
@henrique-thomazi I would like your help to solve the issue. Can I download your app? Since you can consistently reproduce this on your own device, it will be more helpful.
