### ISSUE TITLE
java.lang.IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by AnshulJain1985** [hbb20/CountryCodePickerProject#42]
Hi 

I am getting below error. Its very rare and got only two times.

Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 4, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.hbb20.CountryCodeAdapter$2.onClick(CountryCodeAdapter.java:136)
       at android.view.View.performClick(View.java:4780)
       at android.view.ViewDebug$3.run(ViewDebug.java:826)
       at android.os.Handler.handleCallback(Handler.java:756)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5263)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by hbb20** [comment]
Thanks for reporting.

Surely I will look in to it.
If you can give me following details then it will be a great help to find
the cause:
- library version that you are using.
- entered query if any.
- did you use custom master list?
- did you set preference countries?

**Comment by AnshulJain1985** [comment]
Thanks for looking into the issue.

- I am using 1.7.1
- No I am using default master list
- No I have not set any preferences for countries.
- I am not sure about the query

Let me know if you need any other details.

**Comment by hbb20** [comment]
Thanks. This should be enough. I will let you know if further help is
needed.

**Comment by hbb20** [comment]
Could not find exact cause. 
Possible cause is handled. It should not occur for next version greater than 1.7.7.

**Comment by ogasimli** [comment]
I encountered the exact same crash. Device crashing is running on Android 5. Library version is 2.0.5. I have set preference countries: AZ, AE, US. I don't know if it is a persistent crash, but assume that it is not, because the crash event happened only once.
