### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by SerggioC** [hbb20/CountryCodePickerProject#475]
I'm getting this weird crash from always the same device - Lenovo Tab M10 HD (2nd Gen) with Android 10.
Anyone having this device can test?
What can be the issue here?

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String com.hbb20.CCPCountry.getNameCode()' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.hbb20.CCPCountry.getNameCode()' on a null object reference
       at com.hbb20.CountryCodePicker.setCustomDefaultLanguage(CountryCodePicker.java:1064)
       at com.hbb20.CountryCodePicker.changeDefaultLanguage(CountryCodePicker.java:1996)
```

Thanks

**Comment by hbb20** [comment]
No other device? That's weird.

**Comment by SerggioC** [comment]
> No other device? That's weird.
Yep, that's the only device crash showing up in crashlytics.
Can we have a null check in there to solve this issue? Then add the default value.

**Comment by hbb20** [comment]
I absolutely will. But would like to know if there is some edge case that's causing this.

**Comment by hbb20** [comment]
Also, do you use CCP with phone number or as just a country picker?

**Comment by SerggioC** [comment]
I'm creating CountryCodePicker programmatically on button click and showing.
Maybe some defaults are not getting initialized. 
```
CountryCodePicker ccPicker = new CountryCodePicker(activity);
String defaultCountry = Locale.getDefault().getCountry();
if (defaultCountry.isEmpty()) {
    defaultCountry = "PT";
    ccPicker.setDefaultCountryUsingNameCode("PT");
}
ccPicker.setCcpDialogShowFlag(true);
ccPicker.setShowFastScroller(true);
ccPicker.setAutoDetectedCountry(true);
ccPicker.setCcpDialogShowNameCode(false);
ccPicker.showCloseIcon(true);
ccPicker.setDialogCornerRaius(activity.getResources().getDisplayMetrics().density * 4);
ccPicker.setCountryPreference("PT,ES,FR,DE,IT,GB,AO");
ccPicker.showFullName(true);
ccPicker.showNameCode(false);
ccPicker.setCcpDialogShowPhoneCode(false);
ccPicker.detectLocaleCountry(true);
CountryCodePicker.Language language = CountryCodePicker.Language.forCountryNameCode(defaultCountry.toLowerCase());
ccPicker.changeDefaultLanguage(language);
ccPicker.launchCountrySelectionDialog();
ccPicker.setOnCountryChangeListener(() -> {...})

```
