### ISSUE TITLE
NoSuchMethodError using libphonenumber v8.8.2

### ISSUE THREAD

**Issue by ryc16** [hbb20/CountryCodePickerProject#96]
NoSuchMethodError for com.sample
                                                             java.lang.NoSuchMethodError: No static method normalizeDigitsOnly(Ljava/lang/String;)Ljava/lang/String; in class Lcom/google/i18n/phonenumbers/PhoneNumberUtil; or its super classes (declaration of 'com.google.i18n.phonenumbers.PhoneNumberUtil' appears in /data/app/com.sample/split_lib_dependencies_apk.apk:classes65.dex)
                                                                 at com.hbb20.CountryCodePicker.updateFormattingTextWatcher(CountryCodePicker.java:548)
                                                                 at com.hbb20.CountryCodePicker.setEditText_registeredCarrierNumber(CountryCodePicker.java:640)
                                                                 at com.hbb20.CountryCodePicker.registerCarrierNumberEditText(CountryCodePicker.java:1154)

**Comment by hbb20** [comment]
A new version of CCP has been published, 2.0.4. In that, we have updated libphonenumber to 8.8.2 that should solve this.

**Comment by hbb20** [comment]
Please comment if the problem is still there.
